In [1]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 9))
print(np.arange(3, 9, 2))


[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [2]:
np.random.seed(0)

arr1 = np.random.randint(10, size=6)
arr2 = np.random.randint(10, size=(3, 4))
arr3 = np.random.randint(10, size=(3, 4, 5))
                         
print(arr1)
print(arr2)
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [3]:
np.random.seed(1)
arr = np.random.randint(10, size=(3, 4))
print(arr)

print("arr ndim = ", arr.ndim)
print("arr shape = ", arr.shape)
print("arr ndim = ", arr.ndim)
print("arr ndim = ", arr.ndim)
print("arr ndim = ", arr.ndim)
print("arr ndim = ", arr.ndim)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
arr ndim =  2
arr shape =  (3, 4)
arr ndim =  2
arr ndim =  2
arr ndim =  2
arr ndim =  2


In [4]:
np.random.seed(1)
arr = np.random.randint(10, size=(6, 8))
print(arr)

arr_sub = arr[:2, :2]

[[5 8 9 5 0 0 1 7]
 [6 9 2 4 5 2 4 2]
 [4 7 7 9 1 7 0 6]
 [9 9 7 6 9 1 0 1]
 [8 8 3 9 8 7 3 6]
 [5 1 9 3 4 8 1 4]]


In [5]:
np.random.seed(3)
arr = np.random.randint(10, size=(6, 8))
print(arr)

arr_sub = arr[:2, :2].copy()
print(arr_sub)

arr_sub[0,0] = 99
print(arr_sub)

[[8 9 3 8 8 0 5 3]
 [9 9 5 7 6 0 4 7]
 [8 1 6 2 2 1 3 5]
 [8 1 8 7 8 1 0 5]
 [4 1 5 4 7 6 0 0]
 [9 2 4 5 8 8 7 5]]
[[8 9]
 [9 9]]
[[99  9]
 [ 9  9]]


In [31]:
arr = np.arrange(1,10)
print(arr, '|n')

grid = arr.reshape(3,3)
print(grid, '|n')

AttributeError: module 'numpy' has no attribute 'arrange'

In [15]:
arr_1 = np.array([[1,2,3],[1,2,3]])
arr_2 = np.array([[4,5,6],[4,5,6]])
arr_3 = np.array([[7,8,9],[7,8,9]])

arr_total = np.concatenate([arr_1, arr_2,arr_3], axis=1)
print(arr_total)

arr_total = np.vstack([arr_1, arr_2,arr_3])
print(arr_total)

arr_total = np.hstack([arr_1, arr_2,arr_3])
print(arr_total)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [27]:
arr = [1,2,3,99,99,3,2,1]
print(arr, '|n')

arr_1, arr_2 = np.split(arr, [5])
print(arr_1, arr_2)

[1, 2, 3, 99, 99, 3, 2, 1] |n
[ 1  2  3 99 99] [3 2 1]
